-- Ecom Image Agent v1 final schema reference.
-- Target: PostgreSQL 16.
-- Source of truth: Alembic head 20260420_04 + SQLAlchemy ORM models.
-- UUID values are generated by the application; pgcrypto/gen_random_uuid() is not required.

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE users (
    id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(100),
    avatar_url VARCHAR(500),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    email_verified BOOLEAN NOT NULL DEFAULT false,
    last_login_at TIMESTAMP WITH TIME ZONE,
    last_login_ip INET,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_users_status CHECK (status IN ('active', 'disabled', 'suspended'))
);
CREATE INDEX ix_users_status_created_at ON users (status, created_at);
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TABLE refresh_tokens (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    device_id VARCHAR(128),
    user_agent VARCHAR(500),
    ip_address INET,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    replaced_by_token_id UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_replaced_by_token_id_refresh_tokens FOREIGN KEY (replaced_by_token_id) REFERENCES refresh_tokens(id) ON DELETE SET NULL
);
CREATE INDEX ix_refresh_tokens_user_id_revoked_at ON refresh_tokens (user_id, revoked_at);
CREATE INDEX ix_refresh_tokens_user_id_expires_at ON refresh_tokens (user_id, expires_at);
CREATE TRIGGER trg_refresh_tokens_updated_at BEFORE UPDATE ON refresh_tokens FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TABLE audit_logs (
    id UUID NOT NULL,
    user_id UUID,
    action VARCHAR(100) NOT NULL,
    object_type VARCHAR(50),
    object_id UUID,
    request_id VARCHAR(64),
    ip_address INET,
    user_agent VARCHAR(500),
    payload JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT fk_audit_logs_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX ix_audit_logs_user_id_created_at ON audit_logs (user_id, created_at);
CREATE INDEX ix_audit_logs_action_created_at ON audit_logs (action, created_at);
CREATE INDEX ix_audit_logs_request_id ON audit_logs (request_id);
CREATE INDEX ix_audit_logs_payload_gin ON audit_logs USING gin (payload);

CREATE TABLE idempotency_keys (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    request_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    response_status INTEGER,
    response_body JSONB,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_idempotency_keys PRIMARY KEY (id),
    CONSTRAINT uq_idempotency_keys_user_id_request_key UNIQUE (user_id, request_key),
    CONSTRAINT fk_idempotency_keys_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX ix_idempotency_keys_expires_at ON idempotency_keys (expires_at);
CREATE INDEX ix_idempotency_keys_user_id_endpoint ON idempotency_keys (user_id, endpoint);

CREATE TABLE tasks (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    title VARCHAR(255),
    platform VARCHAR(50),
    biz_id VARCHAR(100),
    source_task_id UUID,
    parent_task_id UUID,
    current_step VARCHAR(100),
    progress_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
    input_summary JSONB,
    params JSONB,
    runtime_snapshot JSONB,
    result_summary JSONB,
    error_code VARCHAR(100),
    error_message TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    queued_at TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT fk_tasks_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tasks_source_task_id_tasks FOREIGN KEY (source_task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT fk_tasks_parent_task_id_tasks FOREIGN KEY (parent_task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    CONSTRAINT ck_tasks_tasks_task_type CHECK (task_type IN ('main_image', 'detail_page', 'image_edit')),
    CONSTRAINT ck_tasks_tasks_status CHECK (status IN ('pending', 'queued', 'running', 'succeeded', 'failed', 'partial_failed', 'cancelled')),
    CONSTRAINT ck_tasks_progress_percent_range CHECK (progress_percent >= 0 AND progress_percent <= 100),
    CONSTRAINT ck_tasks_retry_count_nonnegative CHECK (retry_count >= 0)
);
CREATE INDEX ix_tasks_user_id_created_at ON tasks (user_id, created_at);
CREATE INDEX ix_tasks_user_id_status ON tasks (user_id, status);
CREATE INDEX ix_tasks_user_id_task_type ON tasks (user_id, task_type);
CREATE INDEX ix_tasks_biz_id ON tasks (biz_id);
CREATE INDEX ix_tasks_source_task_id ON tasks (source_task_id);
CREATE INDEX ix_tasks_parent_task_id ON tasks (parent_task_id);
CREATE INDEX ix_tasks_user_id_queued_at ON tasks (user_id, queued_at);
CREATE INDEX ix_tasks_input_summary_gin ON tasks USING gin (input_summary);
CREATE INDEX ix_tasks_params_gin ON tasks USING gin (params);
CREATE INDEX ix_tasks_runtime_snapshot_gin ON tasks USING gin (runtime_snapshot);
CREATE INDEX ix_tasks_result_summary_gin ON tasks USING gin (result_summary);
CREATE TRIGGER trg_tasks_updated_at BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TABLE task_results (
    id UUID NOT NULL,
    task_id UUID NOT NULL,
    user_id UUID NOT NULL,
    result_type VARCHAR(50) NOT NULL,
    page_no INTEGER,
    shot_no INTEGER,
    version_no INTEGER NOT NULL DEFAULT 1,
    parent_result_id UUID,
    status VARCHAR(32) NOT NULL DEFAULT 'succeeded',
    cos_key VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    width INTEGER,
    height INTEGER,
    prompt_plan JSONB,
    prompt_final JSONB,
    render_meta JSONB,
    qc_status VARCHAR(32),
    qc_score NUMERIC(5, 2),
    is_primary BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_task_results PRIMARY KEY (id),
    CONSTRAINT fk_task_results_task_id_tasks FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_results_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_results_parent_result_id_task_results FOREIGN KEY (parent_result_id) REFERENCES task_results(id) ON DELETE SET NULL,
    CONSTRAINT ck_task_results_task_results_status CHECK (status IN ('pending', 'succeeded', 'failed')),
    CONSTRAINT ck_task_results_task_results_qc_status CHECK (qc_status IS NULL OR qc_status IN ('pending', 'passed', 'review_required', 'failed')),
    CONSTRAINT ck_task_results_page_no_positive CHECK (page_no IS NULL OR page_no > 0),
    CONSTRAINT ck_task_results_shot_no_positive CHECK (shot_no IS NULL OR shot_no > 0),
    CONSTRAINT ck_task_results_version_no_positive CHECK (version_no > 0),
    CONSTRAINT ck_task_results_size_bytes_nonnegative CHECK (size_bytes >= 0),
    CONSTRAINT ck_task_results_width_nonnegative CHECK (width IS NULL OR width >= 0),
    CONSTRAINT ck_task_results_height_nonnegative CHECK (height IS NULL OR height >= 0),
    CONSTRAINT ck_task_results_qc_score_range CHECK (qc_score IS NULL OR (qc_score >= 0 AND qc_score <= 100))
);
CREATE INDEX ix_task_results_task_id_created_at ON task_results (task_id, created_at);
CREATE INDEX ix_task_results_user_id_created_at ON task_results (user_id, created_at);
CREATE INDEX ix_task_results_task_id_result_type ON task_results (task_id, result_type);
CREATE INDEX ix_task_results_parent_result_id ON task_results (parent_result_id);
CREATE INDEX ix_task_results_task_id_page_no_shot_no ON task_results (task_id, page_no, shot_no);
CREATE INDEX ix_task_results_prompt_plan_gin ON task_results USING gin (prompt_plan);
CREATE INDEX ix_task_results_prompt_final_gin ON task_results USING gin (prompt_final);
CREATE INDEX ix_task_results_render_meta_gin ON task_results USING gin (render_meta);
CREATE TRIGGER trg_task_results_updated_at BEFORE UPDATE ON task_results FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TABLE task_assets (
    id UUID NOT NULL,
    task_id UUID NOT NULL,
    user_id UUID NOT NULL,
    role VARCHAR(50) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    source_task_result_id UUID,
    file_name VARCHAR(255),
    cos_key VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    width INTEGER,
    height INTEGER,
    duration_ms INTEGER,
    scan_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    metadata JSONB,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_task_assets PRIMARY KEY (id),
    CONSTRAINT fk_task_assets_task_id_tasks FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assets_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_assets_source_task_result_id_task_results FOREIGN KEY (source_task_result_id) REFERENCES task_results(id) ON DELETE SET NULL,
    CONSTRAINT ck_task_assets_task_assets_scan_status CHECK (scan_status IN ('pending', 'clean', 'blocked')),
    CONSTRAINT ck_task_assets_role_nonempty CHECK (length(role) > 0),
    CONSTRAINT ck_task_assets_source_type_nonempty CHECK (length(source_type) > 0),
    CONSTRAINT ck_task_assets_size_bytes_nonnegative CHECK (size_bytes >= 0),
    CONSTRAINT ck_task_assets_width_nonnegative CHECK (width IS NULL OR width >= 0),
    CONSTRAINT ck_task_assets_height_nonnegative CHECK (height IS NULL OR height >= 0),
    CONSTRAINT ck_task_assets_duration_ms_nonnegative CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_task_assets_sort_order_nonnegative CHECK (sort_order >= 0)
);
CREATE INDEX ix_task_assets_task_id_sort_order ON task_assets (task_id, sort_order);
CREATE INDEX ix_task_assets_user_id_created_at ON task_assets (user_id, created_at);
CREATE INDEX ix_task_assets_task_id_role ON task_assets (task_id, role);
CREATE INDEX ix_task_assets_source_task_result_id ON task_assets (source_task_result_id);
CREATE INDEX ix_task_assets_metadata_gin ON task_assets USING gin (metadata);
CREATE TRIGGER trg_task_assets_updated_at BEFORE UPDATE ON task_assets FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TABLE task_events (
    id UUID NOT NULL,
    task_id UUID NOT NULL,
    user_id UUID NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    level VARCHAR(20) NOT NULL DEFAULT 'info',
    step VARCHAR(100),
    message TEXT NOT NULL,
    payload JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_task_events PRIMARY KEY (id),
    CONSTRAINT fk_task_events_task_id_tasks FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_events_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_task_events_task_events_level CHECK (level IN ('info', 'warning', 'error'))
);
CREATE INDEX ix_task_events_task_id_created_at ON task_events (task_id, created_at);
CREATE INDEX ix_task_events_user_id_created_at ON task_events (user_id, created_at);
CREATE INDEX ix_task_events_task_id_event_type ON task_events (task_id, event_type);
CREATE INDEX ix_task_events_payload_gin ON task_events USING gin (payload);

CREATE TABLE task_usage_records (
    id UUID NOT NULL,
    task_id UUID NOT NULL,
    user_id UUID NOT NULL,
    provider_type VARCHAR(50) NOT NULL,
    provider_name VARCHAR(100) NOT NULL,
    model_name VARCHAR(100),
    action_name VARCHAR(100) NOT NULL,
    request_units INTEGER,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    image_count INTEGER,
    latency_ms INTEGER,
    cost_amount NUMERIC(12, 4),
    cost_currency VARCHAR(10) NOT NULL DEFAULT 'CNY',
    success BOOLEAN NOT NULL DEFAULT true,
    error_code VARCHAR(100),
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_task_usage_records PRIMARY KEY (id),
    CONSTRAINT fk_task_usage_records_task_id_tasks FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_usage_records_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_task_usage_records_request_units_nonnegative CHECK (request_units IS NULL OR request_units >= 0),
    CONSTRAINT ck_task_usage_records_prompt_tokens_nonnegative CHECK (prompt_tokens IS NULL OR prompt_tokens >= 0),
    CONSTRAINT ck_task_usage_records_completion_tokens_nonnegative CHECK (completion_tokens IS NULL OR completion_tokens >= 0),
    CONSTRAINT ck_task_usage_records_image_count_nonnegative CHECK (image_count IS NULL OR image_count >= 0),
    CONSTRAINT ck_task_usage_records_latency_ms_nonnegative CHECK (latency_ms IS NULL OR latency_ms >= 0),
    CONSTRAINT ck_task_usage_records_cost_amount_nonnegative CHECK (cost_amount IS NULL OR cost_amount >= 0)
);
CREATE INDEX ix_task_usage_records_task_id_created_at ON task_usage_records (task_id, created_at);
CREATE INDEX ix_task_usage_records_user_id_created_at ON task_usage_records (user_id, created_at);
CREATE INDEX ix_task_usage_records_provider_type_provider_name ON task_usage_records (provider_type, provider_name);
CREATE INDEX ix_task_usage_records_metadata_gin ON task_usage_records USING gin (metadata);

CREATE TABLE image_edits (
    id UUID NOT NULL,
    source_result_id UUID NOT NULL,
    edit_task_id UUID NOT NULL,
    user_id UUID NOT NULL,
    edited_result_id UUID,
    selection_type VARCHAR(32) NOT NULL DEFAULT 'rectangle',
    selection JSONB NOT NULL,
    instruction TEXT NOT NULL,
    mode VARCHAR(64) NOT NULL DEFAULT 'full_image_constrained_regeneration',
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    error_message TEXT,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT pk_image_edits PRIMARY KEY (id),
    CONSTRAINT fk_image_edits_source_result_id_task_results FOREIGN KEY (source_result_id) REFERENCES task_results(id) ON DELETE CASCADE,
    CONSTRAINT fk_image_edits_edit_task_id_tasks FOREIGN KEY (edit_task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_image_edits_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_image_edits_edited_result_id_task_results FOREIGN KEY (edited_result_id) REFERENCES task_results(id) ON DELETE SET NULL,
    CONSTRAINT ck_image_edits_image_edits_selection_type CHECK (selection_type IN ('rectangle', 'mask')),
    CONSTRAINT ck_image_edits_image_edits_status CHECK (status IN ('pending', 'queued', 'running', 'succeeded', 'failed', 'cancelled')),
    CONSTRAINT ck_image_edits_image_edits_mode CHECK (mode IN ('native_inpainting', 'full_image_constrained_regeneration'))
);
CREATE INDEX ix_image_edits_source_result_id_created_at ON image_edits (source_result_id, created_at);
CREATE INDEX ix_image_edits_user_id_created_at ON image_edits (user_id, created_at);
CREATE INDEX ix_image_edits_edit_task_id ON image_edits (edit_task_id);
CREATE INDEX ix_image_edits_edited_result_id ON image_edits (edited_result_id);
CREATE INDEX ix_image_edits_selection_gin ON image_edits USING gin (selection);
CREATE INDEX ix_image_edits_metadata_gin ON image_edits USING gin (metadata);
CREATE TRIGGER trg_image_edits_updated_at BEFORE UPDATE ON image_edits FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

COMMIT;
